export enum Route {
  myPlaylists = 'my-playlists',
  myVideos = 'my-videos',
  playlist = 'playlist',
  search = 'search',
  tagEdit = 'tag-edit',
  upload = 'upload',
  userEdit = 'user-edit',
  users = 'users',
  video = 'video',
  videoEdit = 'video-edit',
  groups = 'groups',
  passwordReset = 'password-reset',
  watchLater = 'watch-later',
}
