# Declare the base image
FROM node:lts-alpine3.14

WORKDIR /app

COPY ./package.json .
COPY ./tsconfig.json .
COPY ./tsconfig.json ./node_modules


# 6. Run the app
CMD npm install --legacy-peer-deps && npm run buildIgnoreErrors