version: '3.4'

services:
  frontend-build:
    container_name: frontend-build
    build: 
      context: ../frontend
      dockerfile: ./Dockerfile.build
    volumes:
      - frontend:/app
      - ./node_modules:/app/node_modules
      - ./empty:/app/node_modules_build

  api-build:
    container_name: api-build
    build: 
      context: ../backend/Backend
      dockerfile: ./Dockerfile.build
    volumes:
      - backend:/app
      - backend-publish:/publish

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../frontend/
  backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/Backend
  backend-publish:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../backend/Publish